version: '3.3'
services:
  PostgreSQL:
    image: postgres:latest
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db